data:
  metadata_path: data/original/test.csv       # 原始元数据 CSV
  features_path: 
    - outputs/features/test_features.csv  # AE3D 特征 CSV
    - outputs/features/test_features_2p5d.csv  # AE2p5D 特征 CSV

output:
  path: outputs/test_merged.csv

merge:
  old_prefix: 
    - "feature_"
    - "f"

